name: Deploy Frontend

on: 
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'frontend/meet-arctic-front/**' 

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: 'true'    
    defaults:
      run:
        working-directory: ./frontend/meet-arctic-front   
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache: 'npm'
          cache-dependency-path: './frontend/meet-arctic-front/package-lock.json' 

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: npm run build
      
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./frontend/meet-arctic-front/build/
          server-dir: /mta.anderskaev.ru/public/
          exclude: |
            README.md
            **/*.py
            **/__pycache__/**